- name: ec2 laucher
  hosts: launched
  become: true
  connection: local
  tasks:
  - name: terminate old instance
    ec2_instance:
      region: us-west-2
      state: absent
      filters:
        tag:Type: blue
  - name: lanching ec2
    ec2:
      key_name: that-one
      instance_type: t2.medium
      image: ami-0ca853d5eda656374
      region: us-west-2
      wait: yes
      group: launch-wizard-3
      count: 1
      vpc_subnet_id: subnet-c90f0cb0
      assign_public_ip: yes
      instance_tags:
       Type: blue
    register: ec2

  - name: Add new instance to host group
    add_host: hostname={{ item.public_ip }} groupname=launched ansible_ssh_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa
    with_items: '{{ec2.instances}}'
  
  - name: Wait for SSH to come up
    wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
    with_items: '{{ec2.instances}}'
  
- name: Configure instance(s)
  hosts: launched
  gather_facts: True
  tasks:
  - name: git
    yum: name=git state=present
  
  - name: git
    yum: name=git state=present
  
  - name: git
    yum: name=git state=present
  
  - name: docker
    yum: name=docker.io state=present
  
  - name: insatll minikube
    get_url:
      url: curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
  
  - name: give executable permission
    shell:  chmod +x minikube

  


